export const PLATFORM_TOKEN_KEYS = [
  'TELEGRAM_BOT_TOKEN',
  'DISCORD_BOT_TOKEN',
  'SLACK_APP_TOKEN',
  'SLACK_BOT_TOKEN',
  'WHATSAPP_API_TOKEN',
  'SIGNAL_PHONE_NUMBER',
  'MATRIX_ACCESS_TOKEN',
] as const;
